# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "nginx",
        :net => [
           ["192.168.11.150",  2, "255.255.255.0", "mynet"],
        ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        sudo do-release-upgrade
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
      config.vm.define "ubuntu_ansible" do |ubuntu_ansible|
          ubuntu_ansible.vm.box = "ubuntu/jammy64"
          ubuntu_ansible.vm.host_name = "ubuntu"
          ubuntu_ansible.vm.network "private_network", ip: "192.168.11.151", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "mynet"
          ubuntu_ansible.vm.synced_folder ".\\.vagrant\\machines\\nginx\\virtualbox", "/opt/sshkeydata"
          ubuntu_ansible.vm.synced_folder ".\\hosts", "/opt/temphosts/"
          ubuntu_ansible.vm.provider :virtualbox do |vb|
            vb.name = "ubuntu_ansible"
          ubuntu_ansible.vm.provision "shell", inline: <<-SHELL
            sudo -i
            apt update
            apt install software-properties-common
            add-apt-repository --yes --update ppa:ansible/ansible
            apt install --yes ansible
            sudo cp -R /opt/temphosts/ /opt/hosts
            cd /opt/hosts
            cp /opt/sshkeydata/private_key nginx.pem
            sudo chmod 400 nginx.pem
            # sudo ansible nginx -m ping -i inventory
            # echo "Версия ядра: " $(sudo ansible nginx -m command -a "uname -r")
            # sudo ansible nginx -m systemd -a name=firewalld
            # sudo ansible-playbook -vvv nginx.yaml
            # sudo curl http://192.168.11.150:8080
          SHELL
      end
  end
end